---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3118871053-lDd6EiYj7QS5gXQyCy76mHS0eqMtxqQO6DfZARN
:access_token_secret: Uwa7klTv80zmBwOhkbPIh2rusRjxhc8Pv9d8h79OYeEzH
